### ISSUE TITLE
more agent?

### ISSUE THREAD

**Issue by flynnamy** [zcczhang/UAV_Coverage#1]
Hi, have you ever tried to apply this algorithm or explore algorithms to see more agents behaviors,like 3,4,5 or more agents? Could you please give me some suggestions about more agents to do coverage? @zcczhang

**Comment by zcczhang** [comment]
Hi, we have tried 4 agents using ACKTR, and it worked sometimes, but the convergence to the "optimal path" was very unstable. Based on our experiments for one and double agents coverage, rewards, which indicate the balance of coverage and visiting minimal steps under cooperation, were one of the most important parts of this problem. Also, while agents increasing, the action-state space pairs increase tremendously, so parameter setting is also tricky. For the time being, everything for more agents coverage is just in embryo, and we may play with this topic in the near future.

**Comment by zcczhang** [comment]
> Hi, have you ever tried to apply this algorithm or explore algorithms to see more agents behaviors,like 3,4,5 or more agents? Could you please give me some suggestions about more agents to do coverage? @zcczhang

Hi, we have tried 4 agents using ACKTR, and it worked sometimes, but the convergence to the "optimal path" was very unstable. Based on our experiments for one and double agents coverage, rewards, which indicate the balance of coverage and visiting minimal steps under cooperation, were one of the most important parts of this problem. Also, while agents increasing, the action-state space pairs increase tremendously, so parameter setting is also tricky. For the time being, everything for more agents coverage is just in embryo, and we may play with this topic in the near future.

**Comment by flynnamy** [comment]
Yeap,I have tried 3 and 4 agents and found that it is hard to converge. How about apply ACTKR to the hexagon environment?  @zcczhang

**Comment by zcczhang** [comment]
In this case, I believe it is just adding more legal actions corresponding with each state, so based on our experiment, it works for small size hexagon environment.

**Comment by flynnamy** [comment]
Could you please share hexagon experiment? How about small size? Thanks!

**Comment by zcczhang** [comment]
I don't have the code yet(another team member kept that) but it just similar with the gridworld
