### ISSUE TITLE
Past_All_Grids_v2.0.1.ipynb 

### ISSUE THREAD

**Issue by Wujie-nju** [zcczhang/UAV_Coverage#2]
I have run it with "BOARD_ROWS = 5  BOARD_COLS = 6", the results showed that the first path was "up"
![QQ截图20220218203640](https://user-images.githubusercontent.com/85567473/154684193-edf4b106-5002-4217-b54d-303565b0fc5a.png)
.

**Comment by zcczhang** [comment]
As that file is only tested for the tabular Q learning, it is not surprising that it reached some local optimal or fail to approximate the optimal value (policy). Also, you can increase the number of episodes while decreasing a little bit learning rate, and that probably could generate better results.

**Comment by Wujie-nju** [comment]
Thank you very much. When I try the ACTKR method, I set the agent position as follows:
![QQ截图20220222105718](https://user-images.githubusercontent.com/85567473/155054901-ec192957-af2c-4763-85a7-138af8ff497c.png)
The path results cannot coverage the whole Board. How can I solve this condition?
![2](https://user-images.githubusercontent.com/85567473/155055060-706cbdcb-35bf-498c-886a-aeae86b2c006.png)

**Comment by zcczhang** [comment]
Make sure that the problem (environment) is solvable for coverage paths, i.e. with the Hamiltonian cycle. Also, no guarantee for convergence every time due to the less tuned parameters and so forth.
